
GET http://localhost:5000/product/searchproducts
Content-Type: application/json

{
    "searchTerm": "rabvid"
}


###
POST http://localhost:5000/product
Content-Type: application/json

{ "title": "Betadine", 
  "company": "Torrento Pharmaceuticals", 
  "quantity":"10pc", 
  "image": "image_url", 
  "price": "₹ 19.39", 
 "description": "In the PRINCE2 project management method, a product description is a structured format that presents information about a project product. It is a management product, usually created by the project manager during the process of initiating a project in the initial stage of the PRINCE2 project management method." }

# {
#     "title" : "Omez 365",
#     "company":"Mankind",
#     "quantity":"10 pc",
#     "price": "Rs 10",
#     "description" : "lorem ipsum lorem ipsum"
# }

###
GET http://localhost:5000/product/allproducts

###
GET http://localhost:5000/product/getproducts
Content-Type: application/json

{
    "page": 2,
    "pageSize": 10
}

###
POST http://localhost:5000/login
Content-Type: application/json

{
    "username": "newUser",
    "password" : "123"
}

###
POST http://localhost:5000/login/validate
Content-Type: application/json

{
    "username": "Ameya",
    "password" : "123"
}

###
GET http://localhost:5000/login/protected
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7Il9pZCI6IjY1MDk1MjhjMmQxNDI4NDlhMTAzY2ZlOSIsInVzZXJuYW1lIjoiQW1leWEiLCJwYXNzd29yZCI6IiQyYiQxMCRHSmVENVFFdWxlTUgvcWEwYS85ckllM2p3RzMwcnR5MTdKM090QUVuVEIvOWVWbFpwRlUxZSIsIl9fdiI6MH0sImlhdCI6MTY5NTEyNDEwNn0.ehhVnmN9-0c5KLWxZzkAPT-F0WRMc9et5QQBp8FQSdM