
GET http://localhost:5000/product/searchproducts
Content-Type: application/json

{
    "searchTerm": "rabvid"
}


###
POST http://localhost:5000/product
Content-Type: application/json

{ "title": "Betadine", 
  "company": "Torrento Pharmaceuticals", 
  "quantity":"10pc", 
  "image": "image_url", 
  "price": "₹ 19.39", 
 "description": "In the PRINCE2 project management method, a product description is a structured format that presents information about a project product. It is a management product, usually created by the project manager during the process of initiating a project in the initial stage of the PRINCE2 project management method." }

# {
#     "title" : "Omez 365",
#     "company":"Mankind",
#     "quantity":"10 pc",
#     "price": "Rs 10",
#     "description" : "lorem ipsum lorem ipsum"
# }

###
GET http://localhost:5000/product/allproducts

###
GET http://localhost:5000/product/getproducts
Content-Type: application/json

{
    "page": 2,
    "pageSize": 10
}

###
POST http://localhost:5000/login
Content-Type: application/json

{
    "username": "Mayu",
    "password" : "123"
}

###
GET http://localhost:5000/login/getaddressesbyuser
Content-Type: application/json

{
    "username": "Mayu"
}

###
POST http://localhost:5000/login/addnewaddress
Content-Type: application/json

{
    "username": "Mayu",
    "newAddress" : "Sky Home PG, Narayan Nagar, Hinjewadi Phase 1, Pune, Maharashtra - 411057"
}

###
DELETE http://localhost:5000/login/removeAddress
Content-Type: application/json

{
    "username": "Mayu",
    "index": 1
}

###
POST http://localhost:5000/login/validate
Content-Type: application/json

{
    "username": "Ameya",
    "password" : "123"
}

###
GET http://localhost:5000/login/authtest
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjoiQW1leWEiLCJpYXQiOjE2OTU4NDI2NTF9.zF-iUPNQ0K_gS8Z-3hteFAw4o4lduWs6zsniPnwdPgw